-- best to drop tables manually in case data is lost
-- DROP TABLE IF EXISTS `#__blogsters`;
-- DROP TABLE IF EXISTS `#__blogsters_categories`;
-- DROP TABLE IF EXISTS `#__blogsters_votings`;
-- DROP TABLE IF EXISTS `#__blogsters_authors`;
-- DROP TABLE IF EXISTS `#__blogsters_tags`;